- name: install apache and php for Debian serversa
  tags: apache,apache2,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Debian"

- name: install apache and php for CentOS  servers
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: change e-mail address for admin
  tags: apache,apache2,debian
  lineinfile:
    path: /etc/apache2/conf-available/charset.conf
    regexp: '^#AddDefaultCharset'
    line: AddDefaultCharset UTF-8
  when: ansible_distribution == "Debian"
  register: apache2

- name: restart apache2 (Debian)
  tags: apache,apache2,debian
  service:
    name: apache2
    state: restarted
  when: apache2.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

