- name: install apache and php packages
  tags: apache,httpd,php
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache,httpd
  service:
    name:  "{{ apache_service }}"
    state: started
    enabled: yes

- name: Enable default charset in config file
  tags: apache,apache2,debian
  lineinfile:
    path: /etc/apache2/conf-available/charset.conf
    regexp: '^AddDefaultCharset'
    line: "#AddDefaultCharset UTF-8"
  when: ansible_distribution == "Debian"
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

