- name: add ssh key for ansioblebot
  authorized_key:
    user: ansiblebot
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIrAp/RI0yb/yPVRcbgzMDFC6vsBHgkPrDjU46M3Ncvc ansible"

- name: generate sshd_config from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

